// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package tests

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson2d331fe4DecodeGithubComMailruEasyjsonTests(in *jlexer.Lexer, out *EscStringStruct) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "a":
			out.A = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2d331fe4EncodeGithubComMailruEasyjsonTests(out *jwriter.Writer, in EscStringStruct) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"a\":"
		out.RawString(prefix[1:])
		out.String(string(in.A))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EscStringStruct) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2d331fe4EncodeGithubComMailruEasyjsonTests(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EscStringStruct) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2d331fe4EncodeGithubComMailruEasyjsonTests(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EscStringStruct) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2d331fe4DecodeGithubComMailruEasyjsonTests(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EscStringStruct) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2d331fe4DecodeGithubComMailruEasyjsonTests(l, v)
}
func easyjson2d331fe4DecodeGithubComMailruEasyjsonTests1(in *jlexer.Lexer, out *EscIntStruct) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "a":
			out.A = int(in.IntStr())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2d331fe4EncodeGithubComMailruEasyjsonTests1(out *jwriter.Writer, in EscIntStruct) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"a\":"
		out.RawString(prefix[1:])
		out.IntStr(int(in.A))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EscIntStruct) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2d331fe4EncodeGithubComMailruEasyjsonTests1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EscIntStruct) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2d331fe4EncodeGithubComMailruEasyjsonTests1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EscIntStruct) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2d331fe4DecodeGithubComMailruEasyjsonTests1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EscIntStruct) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2d331fe4DecodeGithubComMailruEasyjsonTests1(l, v)
}
