// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package tests

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB97a3efeDecodeGithubComMailruEasyjsonTests(in *jlexer.Lexer, out *NamedType) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Inner":
			easyjsonB97a3efeDecode(in, &out.Inner)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB97a3efeEncodeGithubComMailruEasyjsonTests(out *jwriter.Writer, in NamedType) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Inner\":"
		out.RawString(prefix[1:])
		easyjsonB97a3efeEncode(out, in.Inner)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v NamedType) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB97a3efeEncodeGithubComMailruEasyjsonTests(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v NamedType) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB97a3efeEncodeGithubComMailruEasyjsonTests(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *NamedType) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB97a3efeDecodeGithubComMailruEasyjsonTests(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *NamedType) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB97a3efeDecodeGithubComMailruEasyjsonTests(l, v)
}
func easyjsonB97a3efeDecode(in *jlexer.Lexer, out *struct {
	Field  MyString `tag:"value"`
	Field2 int      "tag:\"value with ` in it\""
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Field":
			out.Field = MyString(in.String())
		case "Field2":
			out.Field2 = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB97a3efeEncode(out *jwriter.Writer, in struct {
	Field  MyString `tag:"value"`
	Field2 int      "tag:\"value with ` in it\""
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Field\":"
		out.RawString(prefix[1:])
		out.String(string(in.Field))
	}
	{
		const prefix string = ",\"Field2\":"
		out.RawString(prefix)
		out.Int(int(in.Field2))
	}
	out.RawByte('}')
}
