// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package tests

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonDd15d5e3DecodeGithubComMailruEasyjsonTests(in *jlexer.Lexer, out *NestedMarshaler) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Value":
			out.Value.UnmarshalEasyJSON(in)
		case "Value2":
			out.Value2 = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonDd15d5e3EncodeGithubComMailruEasyjsonTests(out *jwriter.Writer, in NestedMarshaler) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Value\":"
		out.RawString(prefix[1:])
		in.Value.MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"Value2\":"
		out.RawString(prefix)
		out.Int(int(in.Value2))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v NestedMarshaler) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonDd15d5e3EncodeGithubComMailruEasyjsonTests(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v NestedMarshaler) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonDd15d5e3EncodeGithubComMailruEasyjsonTests(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *NestedMarshaler) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonDd15d5e3DecodeGithubComMailruEasyjsonTests(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *NestedMarshaler) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonDd15d5e3DecodeGithubComMailruEasyjsonTests(l, v)
}
