// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package tests

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson674963abDecodeGithubComMailruEasyjsonTests(in *jlexer.Lexer, out *Struct2) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "from":
			if in.IsNull() {
				in.Skip()
				out.From = nil
			} else {
				if out.From == nil {
					out.From = new(Struct1)
				}
				easyjson674963abDecodeGithubComMailruEasyjsonTests1(in, out.From)
			}
		case "through":
			if in.IsNull() {
				in.Skip()
				out.Through = nil
			} else {
				if out.Through == nil {
					out.Through = new(Struct1)
				}
				easyjson674963abDecodeGithubComMailruEasyjsonTests1(in, out.Through)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson674963abEncodeGithubComMailruEasyjsonTests(out *jwriter.Writer, in Struct2) {
	out.RawByte('{')
	first := true
	_ = first
	if in.From != nil {
		const prefix string = ",\"from\":"
		first = false
		out.RawString(prefix[1:])
		easyjson674963abEncodeGithubComMailruEasyjsonTests1(out, *in.From)
	}
	if in.Through != nil {
		const prefix string = ",\"through\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjson674963abEncodeGithubComMailruEasyjsonTests1(out, *in.Through)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Struct2) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson674963abEncodeGithubComMailruEasyjsonTests(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Struct2) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson674963abEncodeGithubComMailruEasyjsonTests(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Struct2) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson674963abDecodeGithubComMailruEasyjsonTests(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Struct2) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson674963abDecodeGithubComMailruEasyjsonTests(l, v)
}
func easyjson674963abDecodeGithubComMailruEasyjsonTests1(in *jlexer.Lexer, out *Struct1) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson674963abEncodeGithubComMailruEasyjsonTests1(out *jwriter.Writer, in Struct1) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}
