// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package tests

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson66294b56DecodeGithubComMailruEasyjsonTests(in *jlexer.Lexer, out *SnakeStruct) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "weird_http_stuff":
			out.WeirdHTTPStuff = bool(in.Bool())
		case "cUsToM":
			out.CustomNamedField = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson66294b56EncodeGithubComMailruEasyjsonTests(out *jwriter.Writer, in SnakeStruct) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"weird_http_stuff\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.WeirdHTTPStuff))
	}
	{
		const prefix string = ",\"cUsToM\":"
		out.RawString(prefix)
		out.String(string(in.CustomNamedField))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SnakeStruct) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson66294b56EncodeGithubComMailruEasyjsonTests(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SnakeStruct) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson66294b56EncodeGithubComMailruEasyjsonTests(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SnakeStruct) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson66294b56DecodeGithubComMailruEasyjsonTests(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SnakeStruct) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson66294b56DecodeGithubComMailruEasyjsonTests(l, v)
}
