// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package tests

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson27e9271dDecodeGithubComMailruEasyjsonTests(in *jlexer.Lexer, out *TypeDeclared) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Value":
			out.Value = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson27e9271dEncodeGithubComMailruEasyjsonTests(out *jwriter.Writer, in TypeDeclared) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Value\":"
		out.RawString(prefix[1:])
		out.String(string(in.Value))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TypeDeclared) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson27e9271dEncodeGithubComMailruEasyjsonTests(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TypeDeclared) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson27e9271dEncodeGithubComMailruEasyjsonTests(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TypeDeclared) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson27e9271dDecodeGithubComMailruEasyjsonTests(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TypeDeclared) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson27e9271dDecodeGithubComMailruEasyjsonTests(l, v)
}
func easyjson27e9271dDecodeGithubComMailruEasyjsonTests1(in *jlexer.Lexer, out *GenDeclaredWithComment) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Value":
			out.Value = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson27e9271dEncodeGithubComMailruEasyjsonTests1(out *jwriter.Writer, in GenDeclaredWithComment) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Value\":"
		out.RawString(prefix[1:])
		out.String(string(in.Value))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GenDeclaredWithComment) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson27e9271dEncodeGithubComMailruEasyjsonTests1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GenDeclaredWithComment) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson27e9271dEncodeGithubComMailruEasyjsonTests1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GenDeclaredWithComment) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson27e9271dDecodeGithubComMailruEasyjsonTests1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GenDeclaredWithComment) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson27e9271dDecodeGithubComMailruEasyjsonTests1(l, v)
}
func easyjson27e9271dDecodeGithubComMailruEasyjsonTests2(in *jlexer.Lexer, out *GenDeclared1) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Value":
			out.Value = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson27e9271dEncodeGithubComMailruEasyjsonTests2(out *jwriter.Writer, in GenDeclared1) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Value\":"
		out.RawString(prefix[1:])
		out.String(string(in.Value))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GenDeclared1) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson27e9271dEncodeGithubComMailruEasyjsonTests2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GenDeclared1) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson27e9271dEncodeGithubComMailruEasyjsonTests2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GenDeclared1) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson27e9271dDecodeGithubComMailruEasyjsonTests2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GenDeclared1) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson27e9271dDecodeGithubComMailruEasyjsonTests2(l, v)
}
