// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package tests

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6834c296DecodeGithubComMailruEasyjsonTests(in *jlexer.Lexer, out *StructWithUnknownsProxyWithOmitempty) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Field1":
			out.Field1 = string(in.String())
		default:
			out.UnmarshalUnknown(in, key)
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6834c296EncodeGithubComMailruEasyjsonTests(out *jwriter.Writer, in StructWithUnknownsProxyWithOmitempty) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Field1 != "" {
		const prefix string = ",\"Field1\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Field1))
	}
	in.MarshalUnknowns(out, first)
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v StructWithUnknownsProxyWithOmitempty) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6834c296EncodeGithubComMailruEasyjsonTests(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StructWithUnknownsProxyWithOmitempty) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6834c296EncodeGithubComMailruEasyjsonTests(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *StructWithUnknownsProxyWithOmitempty) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6834c296DecodeGithubComMailruEasyjsonTests(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StructWithUnknownsProxyWithOmitempty) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6834c296DecodeGithubComMailruEasyjsonTests(l, v)
}
func easyjson6834c296DecodeGithubComMailruEasyjsonTests1(in *jlexer.Lexer, out *StructWithUnknownsProxy) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Field1":
			out.Field1 = string(in.String())
		default:
			out.UnmarshalUnknown(in, key)
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6834c296EncodeGithubComMailruEasyjsonTests1(out *jwriter.Writer, in StructWithUnknownsProxy) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Field1\":"
		out.RawString(prefix[1:])
		out.String(string(in.Field1))
	}
	in.MarshalUnknowns(out, false)
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v StructWithUnknownsProxy) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6834c296EncodeGithubComMailruEasyjsonTests1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StructWithUnknownsProxy) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6834c296EncodeGithubComMailruEasyjsonTests1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *StructWithUnknownsProxy) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6834c296DecodeGithubComMailruEasyjsonTests1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StructWithUnknownsProxy) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6834c296DecodeGithubComMailruEasyjsonTests1(l, v)
}
